version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    target-branch: "dev"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ":wrench:"
    assignees:
      - "eymankun"
    labels:
      - "dependencies"
      - "github-actions"