name: Build and Push Image

on:
  push:
    tags:
      - 'v*'

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract git tag
              id: git_tag
              run: echo "GIT_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push image
              uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64,linux/arm64
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                    ${{ secrets.DOCKER_USERNAME }}/speedtest:latest
                    ${{ secrets.DOCKER_USERNAME }}/speedtest:${{ env.GIT_TAG }}
